""" made a change to profile model to include attribute sub

Revision ID: 8006f9ff0c12
Revises: f1a7c0cec2bc
Create Date: 2023-01-24 12:14:51.639437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8006f9ff0c12'
down_revision = 'f1a7c0cec2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('sub', sa.Integer(), nullable=True))
    op.drop_column('profile', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('profile', 'sub')
    # ### end Alembic commands ###
