"""added a column for name in profile model

Revision ID: f1a7c0cec2bc
Revises: 81605a53de8b
Create Date: 2023-01-23 18:16:44.842603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1a7c0cec2bc'
down_revision = '81605a53de8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'name')
    # ### end Alembic commands ###
